<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id')->unsigned();
            $table->string('code', 2)->nullable();
            $table->string('title', 255);
        });

        $countries = [
            ['code' => 'CA', 'title' => 'Canada'],
            ['code' => 'AF', 'title' => 'Afghanistan'],
            ['code' => 'AL', 'title' => 'Albania'],
            ['code' => 'DZ', 'title' => 'Algeria'],
            ['code' => 'DS', 'title' => 'American Samoa'],
            ['code' => 'AD', 'title' => 'Andorra'],
            ['code' => 'AO', 'title' => 'Angola'],
            ['code' => 'AI', 'title' => 'Anguilla'],
            ['code' => 'AQ', 'title' => 'Antarctica'],
            ['code' => 'AG', 'title' => 'Antigua and Barbuda'],
            ['code' => 'AR', 'title' => 'Argentina'],
            ['code' => 'AM', 'title' => 'Armenia'],
            ['code' => 'AW', 'title' => 'Aruba'],
            ['code' => 'AU', 'title' => 'Australia'],
            ['code' => 'AT', 'title' => 'Austria'],
            ['code' => 'AZ', 'title' => 'Azerbaijan'],
            ['code' => 'BS', 'title' => 'Bahamas'],
            ['code' => 'BH', 'title' => 'Bahrain'],
            ['code' => 'BD', 'title' => 'Bangladesh'],
            ['code' => 'BB', 'title' => 'Barbados'],
            ['code' => 'BY', 'title' => 'Belarus'],
            ['code' => 'BE', 'title' => 'Belgium'],
            ['code' => 'BZ', 'title' => 'Belize'],
            ['code' => 'BJ', 'title' => 'Benin'],
            ['code' => 'BM', 'title' => 'Bermuda'],
            ['code' => 'BT', 'title' => 'Bhutan'],
            ['code' => 'BO', 'title' => 'Bolivia'],
            ['code' => 'BA', 'title' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'title' => 'Botswana'],
            ['code' => 'BV', 'title' => 'Bouvet Island'],
            ['code' => 'BR', 'title' => 'Brazil'],
            ['code' => 'IO', 'title' => 'British Indian Ocean Territory'],
            ['code' => 'BN', 'title' => 'Brunei Darussalam'],
            ['code' => 'BG', 'title' => 'Bulgaria'],
            ['code' => 'BF', 'title' => 'Burkina Faso'],
            ['code' => 'BI', 'title' => 'Burundi'],
            ['code' => 'KH', 'title' => 'Cambodia'],
            ['code' => 'CM', 'title' => 'Cameroon'],
            ['code' => 'CV', 'title' => 'Cape Verde'],
            ['code' => 'KY', 'title' => 'Cayman Islands'],
            ['code' => 'CF', 'title' => 'Central African Republic'],
            ['code' => 'TD', 'title' => 'Chad'],
            ['code' => 'CL', 'title' => 'Chile'],
            ['code' => 'CN', 'title' => 'China'],
            ['code' => 'CX', 'title' => 'Christmas Island'],
            ['code' => 'CC', 'title' => 'Cocos (Keeling) Islands'],
            ['code' => 'CO', 'title' => 'Colombia'],
            ['code' => 'KM', 'title' => 'Comoros'],
            ['code' => 'CD', 'title' => 'Democratic Republic of the Congo'],
            ['code' => 'CG', 'title' => 'Republic of Congo'],
            ['code' => 'CK', 'title' => 'Cook Islands'],
            ['code' => 'CR', 'title' => 'Costa Rica'],
            ['code' => 'HR', 'title' => 'Croatia (Hrvatska)'],
            ['code' => 'CU', 'title' => 'Cuba'],
            ['code' => 'CY', 'title' => 'Cyprus'],
            ['code' => 'CZ', 'title' => 'Czech Republic'],
            ['code' => 'DK', 'title' => 'Denmark'],
            ['code' => 'DJ', 'title' => 'Djibouti'],
            ['code' => 'DM', 'title' => 'Dominica'],
            ['code' => 'DO', 'title' => 'Dominican Republic'],
            ['code' => 'TP', 'title' => 'East Timor'],
            ['code' => 'EC', 'title' => 'Ecuador'],
            ['code' => 'EG', 'title' => 'Egypt'],
            ['code' => 'SV', 'title' => 'El Salvador'],
            ['code' => 'GQ', 'title' => 'Equatorial Guinea'],
            ['code' => 'ER', 'title' => 'Eritrea'],
            ['code' => 'EE', 'title' => 'Estonia'],
            ['code' => 'ET', 'title' => 'Ethiopia'],
            ['code' => 'FK', 'title' => 'Falkland Islands (Malvinas)'],
            ['code' => 'FO', 'title' => 'Faroe Islands'],
            ['code' => 'FJ', 'title' => 'Fiji'],
            ['code' => 'FI', 'title' => 'Finland'],
            ['code' => 'FR', 'title' => 'France'],
            ['code' => 'FX', 'title' => 'France, Metropolitan'],
            ['code' => 'GF', 'title' => 'French Guiana'],
            ['code' => 'PF', 'title' => 'French Polynesia'],
            ['code' => 'TF', 'title' => 'French Southern Territories'],
            ['code' => 'GA', 'title' => 'Gabon'],
            ['code' => 'GM', 'title' => 'Gambia'],
            ['code' => 'GE', 'title' => 'Georgia'],
            ['code' => 'DE', 'title' => 'Germany'],
            ['code' => 'GH', 'title' => 'Ghana'],
            ['code' => 'GI', 'title' => 'Gibraltar'],
            ['code' => 'GK', 'title' => 'Guernsey'],
            ['code' => 'GR', 'title' => 'Greece'],
            ['code' => 'GL', 'title' => 'Greenland'],
            ['code' => 'GD', 'title' => 'Grenada'],
            ['code' => 'GP', 'title' => 'Guadeloupe'],
            ['code' => 'GU', 'title' => 'Guam'],
            ['code' => 'GT', 'title' => 'Guatemala'],
            ['code' => 'GN', 'title' => 'Guinea'],
            ['code' => 'GW', 'title' => 'Guinea-Bissau'],
            ['code' => 'GY', 'title' => 'Guyana'],
            ['code' => 'HT', 'title' => 'Haiti'],
            ['code' => 'HM', 'title' => 'Heard and Mc Donald Islands'],
            ['code' => 'HN', 'title' => 'Honduras'],
            ['code' => 'HK', 'title' => 'Hong Kong'],
            ['code' => 'HU', 'title' => 'Hungary'],
            ['code' => 'IS', 'title' => 'Iceland'],
            ['code' => 'IN', 'title' => 'India'],
            ['code' => 'IM', 'title' => 'Isle of Man'],
            ['code' => 'ID', 'title' => 'Indonesia'],
            ['code' => 'IR', 'title' => 'Iran (Islamic Republic of)'],
            ['code' => 'IQ', 'title' => 'Iraq'],
            ['code' => 'IE', 'title' => 'Ireland'],
            ['code' => 'IL', 'title' => 'Israel'],
            ['code' => 'IT', 'title' => 'Italy'],
            ['code' => 'CI', 'title' => 'Ivory Coast'],
            ['code' => 'JE', 'title' => 'Jersey'],
            ['code' => 'JM', 'title' => 'Jamaica'],
            ['code' => 'JP', 'title' => 'Japan'],
            ['code' => 'JO', 'title' => 'Jordan'],
            ['code' => 'KZ', 'title' => 'Kazakhstan'],
            ['code' => 'KE', 'title' => 'Kenya'],
            ['code' => 'KI', 'title' => 'Kiribati'],
            ['code' => 'KP', 'title' => 'Korea, Democratic People\'s Republic of'],
            ['code' => 'KR', 'title' => 'Korea, Republic of'],
            ['code' => 'XK', 'title' => 'Kosovo'],
            ['code' => 'KW', 'title' => 'Kuwait'],
            ['code' => 'KG', 'title' => 'Kyrgyzstan'],
            ['code' => 'LA', 'title' => 'Lao People\'s Democratic Republic'],
            ['code' => 'LV', 'title' => 'Latvia'],
            ['code' => 'LB', 'title' => 'Lebanon'],
            ['code' => 'LS', 'title' => 'Lesotho'],
            ['code' => 'LR', 'title' => 'Liberia'],
            ['code' => 'LY', 'title' => 'Libyan Arab Jamahiriya'],
            ['code' => 'LI', 'title' => 'Liechtenstein'],
            ['code' => 'LT', 'title' => 'Lithuania'],
            ['code' => 'LU', 'title' => 'Luxembourg'],
            ['code' => 'MO', 'title' => 'Macau'],
            ['code' => 'MK', 'title' => 'North Macedonia'],
            ['code' => 'MG', 'title' => 'Madagascar'],
            ['code' => 'MW', 'title' => 'Malawi'],
            ['code' => 'MY', 'title' => 'Malaysia'],
            ['code' => 'MV', 'title' => 'Maldives'],
            ['code' => 'ML', 'title' => 'Mali'],
            ['code' => 'MT', 'title' => 'Malta'],
            ['code' => 'MH', 'title' => 'Marshall Islands'],
            ['code' => 'MQ', 'title' => 'Martinique'],
            ['code' => 'MR', 'title' => 'Mauritania'],
            ['code' => 'MU', 'title' => 'Mauritius'],
            ['code' => 'TY', 'title' => 'Mayotte'],
            ['code' => 'MX', 'title' => 'Mexico'],
            ['code' => 'FM', 'title' => 'Micronesia, Federated States of'],
            ['code' => 'MD', 'title' => 'Moldova, Republic of'],
            ['code' => 'MC', 'title' => 'Monaco'],
            ['code' => 'MN', 'title' => 'Mongolia'],
            ['code' => 'ME', 'title' => 'Montenegro'],
            ['code' => 'MS', 'title' => 'Montserrat'],
            ['code' => 'MA', 'title' => 'Morocco'],
            ['code' => 'MZ', 'title' => 'Mozambique'],
            ['code' => 'MM', 'title' => 'Myanmar'],
            ['code' => 'NA', 'title' => 'Namibia'],
            ['code' => 'NR', 'title' => 'Nauru'],
            ['code' => 'NP', 'title' => 'Nepal'],
            ['code' => 'NL', 'title' => 'Netherlands'],
            ['code' => 'AN', 'title' => 'Netherlands Antilles'],
            ['code' => 'NC', 'title' => 'New Caledonia'],
            ['code' => 'NZ', 'title' => 'New Zealand'],
            ['code' => 'NI', 'title' => 'Nicaragua'],
            ['code' => 'NE', 'title' => 'Niger'],
            ['code' => 'NG', 'title' => 'Nigeria'],
            ['code' => 'NU', 'title' => 'Niue'],
            ['code' => 'NF', 'title' => 'Norfolk Island'],
            ['code' => 'MP', 'title' => 'Northern Mariana Islands'],
            ['code' => 'NO', 'title' => 'Norway'],
            ['code' => 'OM', 'title' => 'Oman'],
            ['code' => 'PK', 'title' => 'Pakistan'],
            ['code' => 'PW', 'title' => 'Palau'],
            ['code' => 'PS', 'title' => 'Palestine'],
            ['code' => 'PA', 'title' => 'Panama'],
            ['code' => 'PG', 'title' => 'Papua New Guinea'],
            ['code' => 'PY', 'title' => 'Paraguay'],
            ['code' => 'PE', 'title' => 'Peru'],
            ['code' => 'PH', 'title' => 'Philippines'],
            ['code' => 'PN', 'title' => 'Pitcairn'],
            ['code' => 'PL', 'title' => 'Poland'],
            ['code' => 'PT', 'title' => 'Portugal'],
            ['code' => 'PR', 'title' => 'Puerto Rico'],
            ['code' => 'QA', 'title' => 'Qatar'],
            ['code' => 'RE', 'title' => 'Reunion'],
            ['code' => 'RO', 'title' => 'Romania'],
            ['code' => 'RU', 'title' => 'Russian Federation'],
            ['code' => 'RW', 'title' => 'Rwanda'],
            ['code' => 'KN', 'title' => 'Saint Kitts and Nevis'],
            ['code' => 'LC', 'title' => 'Saint Lucia'],
            ['code' => 'VC', 'title' => 'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'title' => 'Samoa'],
            ['code' => 'SM', 'title' => 'San Marino'],
            ['code' => 'ST', 'title' => 'Sao Tome and Principe'],
            ['code' => 'SA', 'title' => 'Saudi Arabia'],
            ['code' => 'SN', 'title' => 'Senegal'],
            ['code' => 'RS', 'title' => 'Serbia'],
            ['code' => 'SC', 'title' => 'Seychelles'],
            ['code' => 'SL', 'title' => 'Sierra Leone'],
            ['code' => 'SG', 'title' => 'Singapore'],
            ['code' => 'SK', 'title' => 'Slovakia'],
            ['code' => 'SI', 'title' => 'Slovenia'],
            ['code' => 'SB', 'title' => 'Solomon Islands'],
            ['code' => 'SO', 'title' => 'Somalia'],
            ['code' => 'ZA', 'title' => 'South Africa'],
            ['code' => 'GS', 'title' => 'South Georgia South Sandwich Islands'],
            ['code' => 'SS', 'title' => 'South Sudan'],
            ['code' => 'ES', 'title' => 'Spain'],
            ['code' => 'LK', 'title' => 'Sri Lanka'],
            ['code' => 'SH', 'title' => 'St. Helena'],
            ['code' => 'PM', 'title' => 'St. Pierre and Miquelon'],
            ['code' => 'SD', 'title' => 'Sudan'],
            ['code' => 'SR', 'title' => 'Suriname'],
            ['code' => 'SJ', 'title' => 'Svalbard and Jan Mayen Islands'],
            ['code' => 'SZ', 'title' => 'Swaziland'],
            ['code' => 'SE', 'title' => 'Sweden'],
            ['code' => 'CH', 'title' => 'Switzerland'],
            ['code' => 'SY', 'title' => 'Syrian Arab Republic'],
            ['code' => 'TW', 'title' => 'Taiwan'],
            ['code' => 'TJ', 'title' => 'Tajikistan'],
            ['code' => 'TZ', 'title' => 'Tanzania, United Republic of'],
            ['code' => 'TH', 'title' => 'Thailand'],
            ['code' => 'TG', 'title' => 'Togo'],
            ['code' => 'TK', 'title' => 'Tokelau'],
            ['code' => 'TO', 'title' => 'Tonga'],
            ['code' => 'TT', 'title' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'title' => 'Tunisia'],
            ['code' => 'TR', 'title' => 'Turkey'],
            ['code' => 'TM', 'title' => 'Turkmenistan'],
            ['code' => 'TC', 'title' => 'Turks and Caicos Islands'],
            ['code' => 'TV', 'title' => 'Tuvalu'],
            ['code' => 'UG', 'title' => 'Uganda'],
            ['code' => 'UA', 'title' => 'Ukraine'],
            ['code' => 'AE', 'title' => 'United Arab Emirates'],
            ['code' => 'GB', 'title' => 'United Kingdom'],
            ['code' => 'US', 'title' => 'United States'],
            ['code' => 'UM', 'title' => 'United States minor outlying islands'],
            ['code' => 'UY', 'title' => 'Uruguay'],
            ['code' => 'UZ', 'title' => 'Uzbekistan'],
            ['code' => 'VU', 'title' => 'Vanuatu'],
            ['code' => 'VA', 'title' => 'Vatican City State'],
            ['code' => 'VE', 'title' => 'Venezuela'],
            ['code' => 'VN', 'title' => 'Vietnam'],
            ['code' => 'VG', 'title' => 'Virgin Islands (British)'],
            ['code' => 'VI', 'title' => 'Virgin Islands (U.S.)'],
            ['code' => 'WF', 'title' => 'Wallis and Futuna Islands'],
            ['code' => 'EH', 'title' => 'Western Sahara'],
            ['code' => 'YE', 'title' => 'Yemen'],
            ['code' => 'ZM', 'title' => 'Zambia'],
            ['code' => 'ZW', 'title' => 'Zimbabwe']
        ];
        DB::table('countries')->insert($countries);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
