<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class FixBrokenQuestionsAfterPrevQuestionsMigration extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        /* DB dump exported as PHP array
            SELECT `id`, `question` FROM `question` WHERE `id` IN (
                1614, 1615, 1616, 1665, 1666, 1667, 1668, 1669, 1676, 1677,
                1678, 1679, 1680, 1682, 1683, 1684, 1685, 1686, 1687, 1688,
                2054, 2080, 2183, 2185, 2187, 2188, 2189, 2190, 2191, 2192,
                2193, 2194, 2195, 2196, 2197, 2199, 2200, 2201, 2202, 2207,
                2208, 2209, 2210, 2211, 2331, 2370, 2371, 2372, 2373, 2940,
                2941, 2955, 2956, 2957, 2958, 2992, 3023, 3041, 3049, 3057,
                3215, 3216, 3217, 3218, 3219, 3221, 3222, 3242, 3243, 3244,
                3245, 3246, 3247, 3248, 3383, 3384, 3385, 3390, 3408, 3411,
                3412, 3413, 3414, 3415, 3417, 3418, 3419, 3420, 3421, 3422,
                3423, 3432, 3439, 3440, 3441, 3462, 3463, 3464, 3497, 3498,
                3499, 3504, 3506, 3597, 3598, 3599, 3602, 3616, 3617, 3618,
                3619, 3620, 3621, 3622, 3626, 3627, 3628, 3629, 3630, 3631,
                3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3664, 3665,
                3666, 3667, 3668, 3669, 3670, 3675, 3676, 3677, 3678, 3679,
                3680, 3681, 3682, 3683, 3787, 3865, 3882, 4078, 4202, 4226,
                4315, 4787, 4788, 4892, 4893, 4894, 4896, 4897, 4899, 4900,
                4901, 4903, 4904, 4905, 4906
            );
        */
        $old_questions = array(
            array('id' => '1614','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em> pressure, or as a fraction <em>systolic/diastolic</em>. According to the following chart</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517292871_blood_pressure.jpg" style="height:282px; width:188px" /></p><p>a person with the blood pressure of 85 over 58 has</p><p>&nbsp;</p>'),
            array('id' => '1615','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em> pressure, or as a fraction <em>systolic/diastolic</em>. According to the following chart</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517293059_blood_pressure.jpg" style="height:275px; width:182px" /></p><p>the person with blood pressure 110/70 has</p>'),
            array('id' => '1616','question' => '<p>According to this chart</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517293230_blood_pressure.jpg" style="height:279px; width:185px" /></p><p>a person with systolic pressure of 150 has</p>'),
            array('id' => '1665','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461075_pie1s.jpg" style="height:88px; width:188px" /></p><p>Roughly what percent of all deaths is due to a heart disease?</p>'),
            array('id' => '1666','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461144_pie1s.jpg" style="height:91px; width:194px" /></p><p>What percent of all deaths is due to respiratory diseases?</p>'),
            array('id' => '1667','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461257_pie1s.jpg" style="height:81px; width:173px" /></p><p>More Canadians die from stroke than from respiratory diseases.</p>'),
            array('id' => '1668','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461359_pie1s.jpg" style="height:67px; width:143px" /></p><p>Roughly, what percent of all deaths is due to respiratory disease and stroke combined?</p>'),
            array('id' => '1669','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461536_pie1s.jpg" style="height:74px; width:158px" /></p><p>More Canadians die from heart disease than from stroke, respiratory disease, and accidents combined.</p>'),
            array('id' => '1676','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" style="height:118px; width:194px" /></p><p>How many children were admitted between 7am and 8am?</p>'),
            array('id' => '1677','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502614_barchart1.jpg" style="height:109px; width:179px" /></p><p>No adults were admitted between 5 am and 6 am.</p>'),
            array('id' => '1678','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502685_barchart1.jpg" style="height:120px; width:197px" /></p><p>How many adults were admitted between 8 am and 9 am?</p>'),
            array('id' => '1679','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502768_barchart1.jpg" style="height:113px; width:186px" /></p><p>How many childern, alltogether, have been admitted between 5 am and 8 am?</p>'),
            array('id' => '1680','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502855_barchart1.jpg" style="height:106px; width:174px" /></p><p>How many adults were admitted between 6am and 9 am?</p>'),
            array('id' => '1682','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517505375_barchart1.jpg" style="height:118px; width:194px" /></p><p>Between 5am and 7am, the unit admitted more adults than children.</p>'),
            array('id' => '1683','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506622_barchart2simple.jpg" style="height:121px; width:171px" /></p><p>The smallest number of new influenza cases was reported on 16 January.</p>'),
            array('id' => '1684','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.<br /><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506740_barchart2simple.jpg" style="height:109px; width:154px" /></p><p>About the same number of new influenza cases were reported on 12 January and 15 January.</p>'),
            array('id' => '1685','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506815_barchart2simple.jpg" style="height:149px; width:209px" /></p><p>The largest drop in the number of new influenza cases reported occured between 15 and 16 January.</p>'),
            array('id' => '1686','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506908_barchart2simple.jpg" style="height:95px; width:134px" /></p><p>What is the total number of new cases reported on 15 and 16 January?</p>'),
            array('id' => '1687','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517507014_barchart2simple.jpg" style="height:146px; width:204px" /></p><p>Estimate the size of the largest day-to-day increase in the number of new cases reported.</p>'),
            array('id' => '1688','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517507204_barchart2simple.jpg" style="height:113px; width:159px" /></p><p>On 14 January, more new cases were reported than on the previous two days combined.</p>'),
            array('id' => '2054','question' => '<p><strong>TEST QUESTION = 0.5</strong></p><p>%%chart{type:4; value:0; marks:0, 0.5, 1; step:0.5; main-color: #F7F7F7; selected-color: #FF4444; stroke-color: #111111; stroke-width:3; mark-diameter:8; point-diameter:3; value-display-chart:1; value-display:1; control: 0}%%</p>'),
            array('id' => '2080','question' => '<p>Canada&#39;s Food Guide recommends 6 servings of grain products for a 17-year old female. By looking at the chart below, determine which of the following choices provides the recommended number of servings of grain products.</p><p><img alt="" style="height:191px; width:335px" src="https://healthnumeracyproject.com/admin/uploads/1529353063_servinggrainMED.jpg" /></p>'),
            array('id' => '2183','question' => '<p>Take a look at this bar chart showing a preferred mode of transportation among young people.</p><p><img alt="" style="height: 249px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1585096769_transportation.jpg" /></p><p>True or False: Bikes were by far the most popular mode of transportation with over 250 individuals using bikes.</p><p>&nbsp;</p>'),
            array('id' => '2185','question' => '<p>Take a look at the bar chart below and decide whether the statement provided is true based on the information given in the chart.</p><p><img alt="" style="height: 202px; width: 280px;" src="https://healthnumeracyproject.com/admin/uploads/1585097262_selfperceivedhealth.jpg" /></p><p>True or False: More than half of the respondents said that their health is very good or excellent.</p>'),
            array('id' => '2187','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" style="height: 156px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517506622_barchart2simple.jpg" /></p><p>True or False: The largest drop in the number of new influenza cases was reported on 16 January.</p>'),
            array('id' => '2188','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506740_barchart2simple.jpg" /></p><p>True or False: About the same number of new influenza cases were reported on 12 January and 15 January.</p>'),
            array('id' => '2189','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506815_barchart2simple.jpg" /></p><p>The largest drop in the number of new influenza cases reported occured between 15 and 16 January.</p>'),
            array('id' => '2190','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" style="height: 156px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517506908_barchart2simple.jpg" /></p><p>What is the total number of new cases reported on 15 and 16 January?</p>'),
            array('id' => '2191','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" style="height: 156px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517507014_barchart2simple.jpg" /></p><p>Estimate the size of the largest day-to-day increase in the number of new cases reported.</p>'),
            array('id' => '2192','question' => '<p>The following chart shows the number of new influenza cases reported during a small-size epidemic in January 2016 in Toronto.</p><p><img alt="" style="height: 156px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517507204_barchart2simple.jpg" /></p><p>On 14 January, more new cases were reported than on the previous two days combined.</p>'),
            array('id' => '2193','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461257_pie1s.jpg" /></p><p>More Canadians die from stroke than from respiratory diseases.</p>'),
            array('id' => '2194','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" style="height: 155px; width: 330px;" src="https://healthnumeracyproject.com/admin/uploads/1517461536_pie1s.jpg" /></p><p>True or False: More Canadians die from heart disease than from stroke, respiratory disease, and accidents combined.</p>'),
            array('id' => '2195','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461075_pie1s.jpg" /></p><p>&nbsp;</p><p>Roughly what percent of all deaths is due to a heart disease?</p>'),
            array('id' => '2196','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" style="height: 160px; width: 340px;" src="https://healthnumeracyproject.com/admin/uploads/1517461144_pie1s.jpg" /></p><p>What percent of all deaths is due to other causes? [Enter your answer without the % sign.]</p>'),
            array('id' => '2197','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" style="height: 160px; width: 340px;" src="https://healthnumeracyproject.com/admin/uploads/1517461359_pie1s.jpg" /></p><p>Roughly, what percent of all deaths is due to respiratory disease?</p>'),
            array('id' => '2199','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" style="height: 134px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>True or False: More adults were admitted between 5 am and 6 am.</p>'),
            array('id' => '2200','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" style="height: 264px; width: 433px;" src="https://healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>How many adults were admitted between 8 am and 9 am?</p>'),
            array('id' => '2201','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>How many children, alltogether, have been admitted between 5 am and 8 am?</p>'),
            array('id' => '2202','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p>&nbsp;</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>How many adults were admitted between 6am and 9 am?</p>'),
            array('id' => '2207','question' => '<p>Blood pressure is reported as&nbsp;&nbsp;<em>systolic over diastolic</em>&nbsp;pressure, or as a fraction <em>systolic/diastolic</em>. According to the following chart</p><p><img alt="" style="width: 190px; height: 287px;" src="https://healthnumeracyproject.com/admin/uploads/1517292871_blood_pressure.jpg" /></p><p>a person with the blood pressure of 85 over 65 has</p>'),
            array('id' => '2208','question' => '<p>Blood pressure is reported as&nbsp;&nbsp;<em>systolic over diastolic</em>&nbsp;pressure, or as a fraction <em>systolic/diastolic</em>. According to the following chart</p><p><img alt="" style="height: 287px; width: 190px;" src="https://healthnumeracyproject.com/admin/uploads/1517292871_blood_pressure.jpg" /></p><p>&nbsp;</p><p>a person with the blood pressure of 110/70&nbsp;has</p>'),
            array('id' => '2209','question' => '<p>Blood pressure is reported as&nbsp;&nbsp;<em>systolic over diastolic</em>&nbsp;pressure, or as a fraction <em>systolic/diastolic</em>. According to the following chart</p><p><img alt="" style="height: 287px; width: 190px;" src="https://healthnumeracyproject.com/admin/uploads/1517292871_blood_pressure.jpg" /></p><p>a person with systolic pressure of 150 has</p>'),
            array('id' => '2210','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em>&nbsp;pressure, often as a rate&nbsp;<em>systolic/diastolic</em>.</p><p><img alt="" style="height: 362px; width: 240px;" src="https://healthnumeracyproject.com/admin/uploads/1517292871_blood_pressure.jpg" /></p><p>True or false: According to this chart, a person whose top number is 110 might have high blood pressure</p>'),
            array('id' => '2211','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em>&nbsp;pressure, or as a fraction <em>systolic/diastolic</em>. According to the following chart</p><p><img alt="" style="height: 287px; width: 190px;" src="https://healthnumeracyproject.com/admin/uploads/1517292871_blood_pressure.jpg" /></p><p>a person with the blood pressure of 85 over 58 has</p>'),
            array('id' => '2331','question' => '<p>Take a look at the bar chart carefully and decide whether the statement below is correct.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1531917970_compare means trial1.png" style="height:344px; width:429px" /></p><p>&nbsp;</p><p>This bar chart shows a comparison of&nbsp;&nbsp;rates.</p>'),
            array('id' => '2370','question' => '<p>Canada&#39;s Food Guide recommends 4 servings of grain products for a 5-year old girl. By looking at the chart below, determine which of the following choices provides the recommended number of servings of grain products.</p><p><img alt="" style="height:191px; width:335px" src="https://healthnumeracyproject.com/admin/uploads/1529353063_servinggrainMED.jpg" /></p>'),
            array('id' => '2371','question' => '<p>Canada&#39;s Food Guide recommends 3 servings of milk and alternatives for a 67-year old female. By looking at the chart below, determine which of the following choices provides the recommended number of servings of milk and alternatives.</p><p><img alt="" style="height:120px; width:335px" src="https://healthnumeracyproject.com/admin/uploads/1534479051_servingmilkMED.jpg" /></p>'),
            array('id' => '2372','question' => '<p>Canada&#39;s Food Guide recommends 3 servings of meat and alternatives for a 17-year old male. By looking at the chart below, determine which of the following choices provides the recommended number of servings of meat and alternatives.</p><p><img alt="" style="height:157px; width:332px" src="https://healthnumeracyproject.com/admin/uploads/1534479229_servingmeatMED.jpg" /></p>'),
            array('id' => '2373','question' => '<p>Canada&#39;s Food Guide recommends 7 servings of vegetables and fruit for a 16-year old female. By looking at the chart below, determine which of the following choices provides the recommended number of servings of vegetables and fruit.</p><p><img alt="" style="height:167px; width:334px" src="https://healthnumeracyproject.com/admin/uploads/1534479431_servingvegetablesMED.jpg" /></p>'),
            array('id' => '2940','question' => '<p>Consider the age distribution in Canada, visualized as a population pyramid</p><p><img alt="" style="height:565px; width:508px" src="https://healthnumeracyproject.com/admin/uploads/1557330203_poppyramidcanadaMED.jpg" /></p><p>According to the 2016 Census (Statistics Canada), the female to male ratio is 100:97 (i.e., 97 males for 100 females). According to this chart, in every age category 60 or above, females outnumber males.</p>'),
            array('id' => '2941','question' => '<p>Consider the age distribution in Canada, visualized as a population pyramid</p><p><img alt="" style="height:565px; width:508px" src="https://healthnumeracyproject.com/admin/uploads/1557330600_poppyramidcanadaMED.jpg" /></p><p>Assume that the female to male ratio is 50:50. According to this chart, in every age category 65 or above, women outnumber men.</p>'),
            array('id' => '2955','question' => '<p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:14px;">The following chart compares the percentage of deaths in Canada by age, for three different times: 1921, 2011, and the mid-point, 1966.</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 418px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1558055445_percentofdeathbyage.jpg" /></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:14px;">Which of the following statements are true?</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:14px;">(A) 1921 had the highest proportion of newborn deaths</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:14px;">(B) In 1921 most deaths occurred over a wide range of years, compared to deaths in 2011 that were more concentrated in a narrower range of ages</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:14px;">(C) Between 1966 and 2011, the most common age at death increased by about 10 years</span></span></p><p>&nbsp;</p>'),
            array('id' => '2956','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart compares the percentage of deaths in Canada by age, for three different times: 1921, 2011, and the mid-point, 1966.</span></span></p><p><img alt="" style="height: 418px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1558055445_percentofdeathbyage.jpg" /></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">True or False: The peaks of the distributions become higher and higher over time, suggesting that survival to older ages is more common in 2011 than in 1921 or 1966.</span></span></p><p>&nbsp;</p><p>&nbsp;</p>'),
            array('id' => '2957','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart depicts the year gained in life expectancy at birth for three age groups and three 30-year intervals.</span></span></p><p><img alt="" style="height: 468px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1558056934_yearsgainedinlifeexp.jpg" /></p><p>True or false: the largest gain in life expectancy at birth for children ages 0 to 4 was between 1921 and 1951.</p><p>&nbsp;</p>'),
            array('id' => '2958','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart depicts the year gained in life expectancy at birth for three age groups and three 30-year intervals.</span></span></p><p><img alt="" style="height: 468px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1558056934_yearsgainedinlifeexp.jpg" /></p><p>True or false: the gains in life expectancy at birth for the entire Canadian population are decreasing (slowing down) over time.</p><p>&nbsp;</p>'),
            array('id' => '2992','question' => '<p>The following pie chart, redrawn from the article <em>Allergic conjunctivitis in Jos-Nigeria,</em> published in Nigerian Medical Journal,&nbsp;represents age distribution of patients diagnosed with allergic conjunctivitis.</p><p><img alt="" style="height:235px; width:440px" src="http://healthnumeracyproject.com/admin/uploads/1558410959_ageconjuctivitiscolour.jpg" /></p><p>(Note that there is a total of 100 patients represented in this chart).</p><p>What is the probability that a random person from this group of 100 patients diagnosed with allergic conjunctivitis is older that 50 years?</p>'),
            array('id' => '3023','question' => '<p>The following pie chart, redrawn from the article <em>Pediatric Allergic Rhinitis,</em> published in Medscape,&nbsp;gives a relative frequency distribution (i.e., percentages) of answers by 2,500 people with nasal allergies to the question &quot;During allergy season, would you say that the condition impacted your life&quot;</p><p><img alt="" style="height: 417px; width: 1033px;" src="https://healthnumeracyproject.com/admin/uploads/1558411289_impactnasalallergiescolour.jpg" /></p><p>What is the chance that a randomly selected person from this group of 2,500 people claims that their nasal allergy had some effect on their life?</p>'),
            array('id' => '3041','question' => '<p>The following pie chart, redrawn from the article <em>Pediatric Allergic Rhinitis,</em> published in Medscape, gives a relative frequency distribution (i.e., percentages) of answers by 2,500 people with nasal allergies to the question &quot;During allergy season, would you say that the condition impacted your life&quot;</p><p><img alt="" style="height: 417px; width: 1033px;" src="https://healthnumeracyproject.com/admin/uploads/1558411289_impactnasalallergiescolour.jpg" /></p><p>What is the chance that a randomly selected person from this group of 2,500 people claims that their nasal allergy had no impact on their life?</p>'),
            array('id' => '3049','question' => '<p>The following pie chart, redrawn from the article <em>Pediatric Allergic Rhinitis,</em> published in Medscape, gives a relative frequency distribution (i.e., percentages) of answers by 2,500 people with nasal allergies to the question &quot;During allergy season, would you say that the condition impacted your life&quot;</p><p><img alt="" style="height: 417px; width: 1033px;" src="https://healthnumeracyproject.com/admin/uploads/1558411289_impactnasalallergiescolour.jpg" /></p><p>What is the chance that a randomly selected person from this group of 2,500 people claims that their nasal allergy had little or no effect on their life?</p>'),
            array('id' => '3057','question' => '<p>The following pie chart&nbsp;represents the age distribution of 100 patients diagnosed with allergic conjunctivitis.</p><p><img alt="" style="height:235px; width:440px" src="https://healthnumeracyproject.com/admin/uploads/1558410959_ageconjuctivitiscolour.jpg" /></p><p>What is the probability that a random person from this group of 100 patients diagnosed with allergic conjunctivitis is 20 years of age or younger?</p>'),
            array('id' => '3215','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart shows the relative risk (likelihood) of a substantial (i.e., at least 10%) increase in the body mass index, by immigrant status, compared to the Canadian-born population.</span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 284px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1559621668_immigratsbmi.jpg" /></span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: Recent non-European immigrants are almost twice as likely as Canadian-born individuals to have a substantial increase in the body mass index.</span></span></p>'),
            array('id' => '3216','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart shows the relative risk (likelihood) of a substantial (i.e., at least 10%) increase in the body mass index, by immigrant status, compared to the Canadian-born population.</span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 284px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1559621668_immigratsbmi.jpg" /></span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: Recent European immigrants overall have a lesser risk of a substantial increase in the body mass index, compared to Canadian-born individuals.</span></span></p>'),
            array('id' => '3217','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart shows the relative risk (likelihood) of transition from good (or very good, or excellent) to bad (or poor) health, by immigrant status, compared to the Canadian-born population.</span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 278px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1559622357_immigrantshealthtransition.jpg" /></span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: Recent European immigrants have a lesser risk of their health deteriorating, compared to Canadian-born individuals.</span></span></p>'),
            array('id' => '3218','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart shows the relative risk (likelihood) of transition from good (or very good, or excellent) to bad (or poor) health, by immigrant status, compared to the Canadian-born population.</span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 278px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1559622357_immigrantshealthtransition.jpg" /></span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: Over time, the health of European immigrants deteriorates.</span></span></p>'),
            array('id' => '3219','question' => '<p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following chart shows the relative risk (likelihood) of transition from good (or very good, or excellent) to bad (or poor) health, by immigrant status, compared to the Canadian-born population.</span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 278px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1559622357_immigrantshealthtransition.jpg" /></span></span></p><p><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: European and non-European immigrants show the same long-term pattern in health deterioration.</span></span></p>'),
            array('id' => '3221','question' => '<p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1559828821_graphs and charts escape 1.png" style="height:668px; width:837px" /></p><p>Select only the answers that are true.&nbsp; They may all be true or all false.&nbsp; You must get all questions right to get to the next challenge.</p><p>True or False: the bars show that the number of hospitalizations due to opioid poisoning&nbsp;increased by about 1500 over the 5 years.</p><p>True or False:&nbsp; the rate (per 100,000) of hospitalizations due to opioid poisoning&nbsp;in Canada increased from about 14 to 16.5.</p><p>True or False: the line shows an&nbsp;increase in number of hospitalizations due to opioid poisoning.</p><p>True or False: given that the slope of the increase in the rate is similar to the slope of the increase in the number of opioid hospitalizations, the population of Canada was pretty stable over the 5 years.</p>'),
            array('id' => '3222','question' => '<p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1559828821_graphs and charts escape 1.png" style="height:668px; width:837px" /></p><p>Rate the evidence below in how strongly it helps convince that there is an opioid crisis in Canada.</p><p>There may be one false statement in the group of statements.&nbsp; If there is a false statement it should be placed last.</p><p>&nbsp;</p>'),
            array('id' => '3242','question' => '<p>Take a look at the bar chart carefully and decide what kind of story it is trying to tell.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1531917970_compare means trial1.png" style="height:504px; width:629px" /></p><p>&nbsp;</p><p>&nbsp;</p>'),
            array('id' => '3243','question' => '<p>Take a look at the bar chart carefully and decide what type of bar chart it is.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1531917970_compare means trial1.png" style="height:504px; width:629px" /></p><p>&nbsp;</p><p>&nbsp;</p>'),
            array('id' => '3244','question' => '<p>Take a look at the bar chart carefully and read through the classification of story types below.&nbsp; Choose the one that best&nbsp;describes the type of story the graph&nbsp;is trying to tell.</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517506815_barchart2simple.jpg" /></p><p>&nbsp;</p>'),
            array('id' => '3245','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p>&nbsp;</p><p><img alt="" src="http://www.healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>What type of bar chart is it?</p>'),
            array('id' => '3246','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" style="height: 134px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>How many children were admitted between 5 am and 9 am?</p>'),
            array('id' => '3247','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461359_pie1s.jpg" style="height:213px; width:454px" /></p><p>What type of pie chart is this?</p>'),
            array('id' => '3248','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1517461359_pie1s.jpg" style="height:213px; width:454px" /></p><p>What kind of story is it trying to tell?</p>'),
            array('id' => '3383','question' => '<p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">The following chart shows age-standardized flu vaccination rates for those aged 12 and older, organized by Canadian provinces and territories to compare 2003 rates with 2013-2014 rates.</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;"><img alt="" style="width: 600px; height: 427px;" src="https://healthnumeracyproject.com/admin/uploads/1561142935_vaccination_rates_canada.jpg" /></span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">True or False: Nova Scotia and New Brunswick had the greatest increase in flu vaccination rates between 2003 and 2013-2014. </span></span></p>'),
            array('id' => '3384','question' => '<p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">The following chart shows age-standardized flu vaccination rates for those aged 12 and older, organized by Canadian provinces and territories to compare 2003 rates with 2013-2014 rates.</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;"><img alt="" style="height: 427px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1561142884_vaccination_rates_canada.jpg" /></span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">True or False: Between 2003 and 2013-2014, flu vaccination rates increased in all provinces and territories.</span></span></p>'),
            array('id' => '3385','question' => '<p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">The following chart shows age-standardized flu vaccination rates for those aged 12 and older, organized by Canadian provinces and territories to compare 2003 rates with 2013-2014 rates.</span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;"><img alt="" style="height: 427px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1561142839_vaccination_rates_canada.jpg" /></span></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-size:16px;">True or False: Even though Ontario did not see an improvement in flu vaccinations between 2003 and 2013-2014, Canada as a whole did witness increased vaccination rates.</span></span></p>'),
            array('id' => '3390','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The report <em>Zika Virus in Ontario: An Update</em>, released in October 2017 published a pie chart representing the 295 people who have tested positive for Zika infection in Ontario from 2016 until May 2017.</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height:334px; width:385px" src="https://healthnumeracyproject.com/admin/uploads/1561174435_zikainontario.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False:&nbsp; Almost two thirds of the people who tested positive for zika were females.</span></span></p>'),
            array('id' => '3408','question' => '<p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1559828821_graphs and charts escape 1.png" style="height:668px; width:837px" /></p><p>Rate the evidence below in how strongly it helps convince that there is an opioid crisis in Canada.</p><p>There may be one false statement in the group of statements.&nbsp; If there is a false statement it should be placed last.</p><p>&nbsp;</p>'),
            array('id' => '3411','question' => '<p>Take a look at the bar chart carefully and decide whether the statement below is correct.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1531917970_compare means trial1.png" style="height:504px; width:629px" /></p><p>&nbsp;</p><p>This bar chart shows that widowed/separated/divorced Canadians were more likely to go for walks than to run for exercise.</p>'),
            array('id' => '3412','question' => '<p>Take a look at the this bar chart.</p><p><img alt="" style="height: 202px; width: 280px;" src="https://healthnumeracyproject.com/admin/uploads/1585102944_selfperceivedhealth.jpg" /></p><p>&nbsp;</p><p>True or False: The rate of poor self-perceived health can be read directly from the graph.</p>'),
            array('id' => '3413','question' => '<p>Take a look at the clustered bar chart carefully.&nbsp; It comes from data ons emergency department visit by&nbsp;adults aged 65 and over.</p><p><img alt="" style="height: 254px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1585102375_visitrates.jpg" /></p><p>True or False: This bar chart represents a comparison of rates.</p>'),
            array('id' => '3414','question' => '<p>The following chart shows the frequency of use of a variety of modes of transportation (excluding walking and motorized vehicle) used to get to school.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1530885634_bar.png" style="height:336px; width:419px" /></p><p>True of False: More children came by scooter than by skateboard.</p>'),
            array('id' => '3415','question' => '<p>The following chart shows the level of difficulty in performing daily activities among adults (18 years or older) with mood and/or anxiety disorder(s).</p><p><img alt="" style="height: 221px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1534742563_moodanxiety.jpg" /></p><p>True or&nbsp;False: The adults represented by this chart experience, as a percent, more difficulty with social activities than with bathing or dressing.</p>'),
            array('id' => '3417','question' => '<p>The following chart shows the number of children and adults admitted to an emergency unit at a hospital, between 5 am and 9 am.</p><p><img alt="" style="height: 134px; width: 220px;" src="https://healthnumeracyproject.com/admin/uploads/1517502399_barchart1.jpg" /></p><p>True of False: The number of children admitted is about the same as the number of adults admitted.&nbsp;(i.e., close to 50% each).</p>'),
            array('id' => '3418','question' => '<p>Classify the following pie chart visually, by choosing from the best option below.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1558747469_causesofdeathus.jpg" style="height:318px; width:479px" /></p><p>What type of pie chart is this?</p>'),
            array('id' => '3419','question' => '<p>Classify the following pie chart (created&nbsp;from the Canadian Community Health Survey 2007 data set) visually, by choosing from the best option below.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1561560537_cchs asthma vs flu shot panel pie.png" style="height:326px; width:419px" /></p><p>What type of pie chart is this?</p>'),
            array('id' => '3420','question' => '<p>The following pie chart shows the most common causes of death among Canadians:</p><p><img alt="" style="height: 197px; width: 420px;" src="https://healthnumeracyproject.com/admin/uploads/1517461359_pie1s.jpg" /></p><p>Roughly, what percent of all deaths is due to respiratory disease and stroke combined?&nbsp;</p>'),
            array('id' => '3421','question' => '<p>The following pie chart is from the Canadian Community Health Survey 2007.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1561564663_cchs asthma vs flu shot panel pie.png" style="height:326px; width:419px" /></p><p>Given that we know that about 9% of the Canadian population has asthma, which do you think would be the closest to the overall rate of &#39;ever had a flu shot&#39; = yes in Canada?</p>'),
            array('id' => '3422','question' => '<p>The following pie chart shows a distribution of breast cancer cases among females 18-79 in Canada, organized by the stage at which the diagnosis was established.</p><p><img alt="" style="width: 800px; height: 489px;" src="https://healthnumeracyproject.com/admin/uploads/1585160506_breastcancerbystage.jpg" /></p><p>What percent of all cancer cases are diagnosed at stage 3 or higher?</p>'),
            array('id' => '3423','question' => '<p>The following pie charts visualize the answers to a survey question &quot;Did you have a flu shot&quot; conducted among people who do not have asthma and who have asthma.</p><p><img alt="" style="height: 171px; width: 420px;" src="https://healthnumeracyproject.com/admin/uploads/1585168217_asthmaflushot.jpg" /></p><p>Compared to those who have asthma, how likely is it that those who don&#39;t have asthma had a flu shot?</p>'),
            array('id' => '3432','question' => '<p>This bar chart shows the number of people who had an asthma attack within the last 30 days, organized by age groups.</p><p><img alt="" style="height: 285px; width: 480px;" src="https://healthnumeracyproject.com/admin/uploads/1585538351_agegroups.jpg" /></p><p>Consider 2 groups of people (over 40 vs under 40).&nbsp; How many more individuals who had asthma attacks were under 40?</p>'),
            array('id' => '3439','question' => '<p>The following pie chart shows the breakdown of stage of cancer at diagnosis in Canada (excluding Quebec)</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1561564178_statcan%20distn%20of%20cancer%20cases%20by%20stage.png" style="height:217px; width:442px" /></p><p>What kind of story is it trying to tell?</p>'),
            array('id' => '3440','question' => '<p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1561578148_statscan geographic distn popn.png" style="height:322px; width:432px" /></p><p>What kind of story is the pie chart trying to tell?</p>'),
            array('id' => '3441','question' => '<p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1561578320_statcan cannabis frequency pie ring.png" style="height:320px; width:446px" /></p><p>What kind of story is the pie chart on frequency of cannabis use trying to tell?</p>'),
            array('id' => '3462','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em>&nbsp;pressure, or as a rate&nbsp;<em>systolic/diastolic</em>.</p><p><img alt="" style="width: 240px; height: 371px;" src="https://healthnumeracyproject.com/admin/uploads/1586312820_bloodpressNEW.jpg" /></p><p>True or False: According to this chart, a person whose diastolic pressure is 55 can have normal blood pressure.</p>'),
            array('id' => '3463','question' => '<p>Take a look at the bar chart carefully and decide what kind of story it is trying to tell.</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1562083750_dementia vs health failure.png" style="height:344px; width:472px" /></p><p>&nbsp;</p><p>&nbsp;</p>'),
            array('id' => '3464','question' => '<p>Take a look at the bar chart carefully and decide what kind of story it is trying to tell.&nbsp;(you may need to make more than one selection)&nbsp;&nbsp;</p><p><img alt="" src="http://healthnumeracyproject.com/admin/uploads/1562084003_smokers rate trend .png" style="height:305px; width:447px" /></p><p>&nbsp;</p><p>&nbsp;</p>'),
            array('id' => '3497','question' => '<p>Look at this bar chart:</p><p><img alt="" style="height:250px; width:474px" src="https://healthnumeracyproject.com/admin/uploads/1585103405_maritalstatus.jpg" /></p><p>True or False: This bar chart shows a comparison of counts of walkers by marital status.</p>'),
            array('id' => '3498','question' => '<p>Students in a grade 12 class were asked the following question &quot;Have you smoked marijunana at school in the last 12 months?&quot; They answers are summarized in the following chart:</p><p><img alt="" style="height: 219px; width: 400px;" src="https://healthnumeracyproject.com/admin/uploads/1585169845_smokeddope.jpg" /></p><p>True or False: About a quarter of the students surveyed said &quot;No.&quot;</p>'),
            array('id' => '3499','question' => '<p>A students in a grade 12 class were asked the following question &quot;Have you smoked marijunana at school in the last 12 months?&quot; They answers are summarized in the following pie charts:</p><p><img alt="" style="height: 191px; width: 560px;" src="https://healthnumeracyproject.com/admin/uploads/1585170156_girlsboysdope.jpg" /></p><p>True or False: Boys were more reluctant than girls to answer the question.</p>'),
            array('id' => '3504','question' => '<p>This chart is a summary of a survey in which a large number of people who broke their leg were asked to identify the intenisty of the pain right after the injury.</p><p>What is the range of the values of&nbsp;pain&nbsp; among all respondents?</p><p><img alt="" style="height: 298px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1585537600_painlevels.jpg" /></p>'),
            array('id' => '3506','question' => '<p>This bar chart is a summary of a survey in which approximately 8000 individuals who broke their leg were asked to identify the intensity of the pain right after the injury.</p><p><img style="height: 298px; width: 500px;" alt="" src="https://healthnumeracyproject.com/admin/uploads/1585537600_painlevels.jpg" /></p><p>True or False: A majority of the people who broke their leg identified the pain intensity as 80 or more.</p>'),
            array('id' => '3597','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em>&nbsp;pressure, or as a rate&nbsp;<em>systolic/diastolic</em>.</p><p><img alt="" style="height: 299px; width: 240px;" src="https://healthnumeracyproject.com/admin/uploads/1587088227_T6L11.jpg" /></p><p>True or False: Based on this chart, it is possible for someone with systolic pressure of 170 to have normal blood pressure.</p>'),
            array('id' => '3598','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em>&nbsp;pressure, or as a rate&nbsp;<em>systolic/diastolic</em>.</p><p><img alt="" style="width: 240px; height: 299px;" src="https://healthnumeracyproject.com/admin/uploads/1587088227_T6L11.jpg" /></p><p>True or False: Based on this chart, a person whose diastolic blood pressure is 85 may have Stage 1 Hypertension.</p>'),
            array('id' => '3599','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">Blood pressure is reported as two numbers: <em>systolic and diastolic</em>&nbsp;pressure, or as a rate&nbsp;<em>systolic/diastolic</em>.</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="width: 400px; height: 300px;" src="https://healthnumeracyproject.com/admin/uploads/1587088498_T6L13.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False:&nbsp;Based on this chart, it is impossible for someone with systolic pressure of 130 to have ideal blood pressure.</span></span></p>'),
            array('id' => '3602','question' => '<p>Blood pressure is reported as <em>systolic over diastolic</em>&nbsp;pressure, or as a fraction <em>systolic/diastolic</em>.</p><p><img alt="" style="width: 360px; height: 261px;" src="https://healthnumeracyproject.com/admin/uploads/1587088927_T6L22.jpg" /></p><p>According to this chart, a person with blood pressure 110/75 has</p>'),
            array('id' => '3616','question' => '<p>U.S. data from 1985-1992 found that approximately 30% of measles cases experienced complications, including pneumonia and hospitalization. The following bar chart displays the rates of pneumonia and hospitalization in patients with measles, by age group.</p><p><img alt="" style="height: 283px; width: 325px;" src="https://healthnumeracyproject.com/admin/uploads/1587172595_L1Q3measles.jpg" /></p><p>About what percentage of children with measles under the age of 5 experienced hospitalization as a complication? [Round to the nearest whole number. Enter a number only, do not enter the percent sign.]</p>'),
            array('id' => '3617','question' => '<p>The following bar chart displays the potential years of life lost (PYLL, in thousands) by selected causes of death in Canada from 2014-2016.</p><p><img alt="" style="height: 301px; width: 440px;" src="https://healthnumeracyproject.com/admin/uploads/1587174680_T1L2Q1.jpg" /></p><p>True or False: In females, there were more potential years of life lost from cancer than from accidents, heart disease, and suicide combined.</p>'),
            array('id' => '3618','question' => '<p>The following bar chart displays the potential years of life lost (PYLL, in thousands) by selected causes of death in Canada from 2014-2016.</p><p><img alt="" style="height: 301px; width: 440px;" src="https://healthnumeracyproject.com/admin/uploads/1587174680_T1L2Q1.jpg" /></p><p>Which of the following causes of death led to an approximately equal number of potential years of life lost in males and females?</p>'),
            array('id' => '3619','question' => '<p>This bar chart displays the hospitalization of individuals with Alzheimer&rsquo;s Dementia.</p><p><img alt="" style="height: 280px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1587175263_Hospitalization Alz.jpg" /></p><p>Fill in the blank in the following statement, by choosing the correct option:</p><p>Approximately ___________ individuals with Alzheimer&rsquo;s Dementia were hospitalized for ischemic heart disease compared to gastrointestinal disease?</p>'),
            array('id' => '3620','question' => '<p>The following bar chart displays the number of famine victims (in millions) worldwide, by decade, since the 1920s.</p><p><img alt="" style="height: 280px; width: 360px;" src="https://healthnumeracyproject.com/admin/uploads/1587175549_T1L4Q3.jpg" /></p><p>Estimate the size of the largest decrease in the number of famine victims between consecutive decades.</p>'),
            array('id' => '3621','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following bar chart displays the number of famine victims (in millions) worldwide, by decade, since the 1920s.</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 280px; width: 360px;" src="https://healthnumeracyproject.com/admin/uploads/1587175549_T1L4Q3.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The smallest change in the number of famine victims worldwide took place between which two consecutive decades?</span></span></p>'),
            array('id' => '3622','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following bar chart illustrates famine victims (in millions) worldwide, by decade, since the 1920s.</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 280px; width: 360px;" src="https://healthnumeracyproject.com/admin/uploads/1587175549_T1L4Q3.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">This bar chart compares</span></span></p>'),
            array('id' => '3626','question' => '<p>This bar chart displays the hospitalization of individuals with Alzheimer&rsquo;s Dementia.</p><p><img alt="" style="height: 280px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1587175263_Hospitalization Alz.jpg" /></p><p>This chart compares</p>'),
            array('id' => '3627','question' => '<p>Take a careful look at the bar chart.</p><p><img alt="" style="height: 427px; width: 460px;" src="https://healthnumeracyproject.com/admin/uploads/1587176744_cancermortperc.jpg" /></p><p>This chart compares</p>'),
            array('id' => '3628','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following bar chart illustrates famine victims (in millions) worldwide, by decade, since the 1920s.</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 280px; width: 360px;" src="https://healthnumeracyproject.com/admin/uploads/1587175549_T1L4Q3.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: This chart displays the number of famine victims worldwide per year, since the 1920s.</span></span></p>'),
            array('id' => '3629','question' => '<p>The following bar chart displays the potential years of life lost (PYLL, in thousands) by selected causes of death in Canada from 2014-2016.</p><p><img alt="" style="height: 301px; width: 440px;" src="https://healthnumeracyproject.com/admin/uploads/1587174680_T1L2Q1.jpg" /></p><p>True or False: This chart shows the number of males and females (in thousands) who died from selected causes (including cancer, accidents, and heart disease) in Canada between 2014 and 2016.</p>'),
            array('id' => '3630','question' => '<p>This chart shows the percent distribution of cancer stage at the time of diagnosis, by cancer type in Canada (2011-2015).</p><p><img alt="" style="height: 447px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1586804401_CancerStage2.jpg" /></p><p>True or False: Based on the bar chart, the majority of people diagnosed with pancreatic cancer were diagnosed with Stage II pancreatic cancer.</p>'),
            array('id' => '3631','question' => '<p>The following bar chart shows the percent distribution of cancer stage at the time of diagnosis, by cancer type in Canada (2011-2015).</p><p><img alt="" style="height: 447px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1586804401_CancerStage2.jpg" /></p><p>About what percentage of people diagnosed with liver cancer received a stage III diagnosis? Round to the nearest whole number.</p><p>[Round to the nearest whole number. Enter a number only, do not enter the percent sign.]</p>'),
            array('id' => '3653','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following bar chart shows the average daily number of deaths, by month, in the US in 2017:</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 308px; width: 520px;" src="https://healthnumeracyproject.com/admin/uploads/1587926069_DailyDeaths.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">During which two consecutive months was the average daily number of deaths about the same?</span></span></p>'),
            array('id' => '3654','question' => '<p>The following bar chart shows the age-standardized incidence rates for small cell lung cancers, by stage at diagnosis and geographic region in Canada, 2011-2015:</p><p><img alt="" style="height: 373px; width: 560px;" src="https://healthnumeracyproject.com/admin/uploads/1587945055_SmallCell.jpg" /></p><p>The age-standardized incidence rate for stage III small cell lung cancer was lowest in what province or territory?</p>'),
            array('id' => '3655','question' => '<p>The following pie chart shows the percent distribution of breast cancer cases by stage at diagnosis in females aged 18-79, in Canada, 2011-2015.</p><p><img alt="" style="height: 287px; width: 280px;" src="https://healthnumeracyproject.com/admin/uploads/1588018449_breastcancerED2.jpg" /></p><p>What percentage of breast cancer cases were diagnosed while at Stage II?&nbsp;[Enter your answer without the % sign.]</p>'),
            array('id' => '3656','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following pie chart illustrates the proportion of deaths in Canada in 2016 due to cancer and other causes:</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 251px; width: 360px;" src="https://healthnumeracyproject.com/admin/uploads/1588019019_deathsED2.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">Roughly what percentage of deaths were due to chronic lower respiratory diseases?</span></span></p>'),
            array('id' => '3657','question' => '<p>The following pie chart shows the proportion of dialysis patients in a study who received influenza vaccinations in 2009 and 2010.</p><p><img alt="" style="height: 187px; width: 320px;" src="https://healthnumeracyproject.com/admin/uploads/1588018864_InfluenzavaccED2.jpg" /></p><p>What proportion of patients received influenza vaccinations in both 2009 and 2010?</p>'),
            array('id' => '3658','question' => '<p>The following pie chart illustrates the proportion of deaths in Canada in 2016 due to cancer and other causes:</p><p><img alt="" style="height: 419px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1588019483_deathsED2.jpg" /></p><p>What percentage of deaths were due to heart disease <em>and</em> diabetes? [Enter your answer without the % sign.]</p>'),
            array('id' => '3659','question' => '<p>The following pie chart illustrates the percent distribution of colon cancer cases by stage at diagnosis in Canada, 2011-2015:</p><p><img alt="" style="height: 349px; width: 300px;" src="https://healthnumeracyproject.com/admin/uploads/1588023498_coloncancerED2.jpg" /></p><p>What percent of colon cancer cases were diagnosed at Stage II or higher? [Enter your answer without the % sign.]</p>'),
            array('id' => '3660','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following pie chart shows the ages of people with Alzheimer&rsquo;s Dementia in the U.S. in 2018:</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 287px; width: 450px;" src="https://healthnumeracyproject.com/admin/uploads/1588012755_Alzheimers ED2.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">Estimate the percentage of people with Alzheimer&rsquo;s Dementia were between the ages of 65 and 84?&nbsp;</span></span></p>'),
            array('id' => '3664','question' => '<p>Atopic dermatitis (AD) is a chronic inflammatory skin disease which is highly associated with allergens and IgE reactivity. The following pie chart shows the contribution of allergen sources to IgE sensitization in AD patients in a study.</p><p><img alt="" style="height: 324px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1588012400_Allergen2.jpg" /></p><p>What was the approximate contribution of the allergen source Timothy grass?</p>'),
            array('id' => '3665','question' => '<p>The following pie chart shows the percent distribution of prostate cancer by stage at diagnosis in males in Canada, 2011-2015:</p><p><img alt="" style="height: 277px; width: 260px;" src="https://healthnumeracyproject.com/admin/uploads/1588023729_prostatecancerED2.jpg" /></p><p>True or False: About half of prostate cancer cases were diagnosed at Stage II.</p>'),
            array('id' => '3666','question' => '<p>The following pie chart shows new HIV diagnoses among men in the US by race/ethnicity, 2017:</p><p><img alt="" style="height: 463px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1588012583_hivED2.jpg" /></p><p>Approximately what percentage of new HIV cases were white?</p>'),
            array('id' => '3667','question' => '<p>The following pie chart shows the ages of people with Alzheimer&rsquo;s Dementia in the U.S. in 2018:</p><p><img alt="" style="height: 319px; width: 500px;" src="https://healthnumeracyproject.com/admin/uploads/1588012755_Alzheimers ED2.jpg" /></p><p>Approximately how many people with Alzheimer&rsquo;s Dementia were over 85 years old?</p>'),
            array('id' => '3668','question' => '<p>The following pie chart illustrates the proportion of deaths in Canada in 2016 due to cancer and other causes:</p><p><img alt="" style="height: 251px; width: 360px;" src="https://healthnumeracyproject.com/admin/uploads/1588019019_deathsED2.jpg" /></p><p>Fill in the blank: ________ as many people died of diabetes than of liver disease in 2016.</p>'),
            array('id' => '3669','question' => '<p>The following pie chart illustrates the percent distribution of colon cancer cases by stage at diagnosis in Canada, 2011-2015:</p><p><img alt="" style="height: 349px; width: 300px;" src="https://healthnumeracyproject.com/admin/uploads/1588023498_coloncancerED2.jpg" /></p><p>True or False: About the same number of people were diagnosed with colon cancer at Stage II as those diagnosed at Stage I and an unknown stage combined.</p>'),
            array('id' => '3670','question' => '<p>The following pie chart shows the percent distribution of prostate cancer by stage at diagnosis in males in Canada, 2011-2015:</p><p><img alt="" style="height: 277px; width: 260px;" src="https://healthnumeracyproject.com/admin/uploads/1588023729_prostatecancerED2.jpg" /></p><p>Compared to those diagnosed with prostate cancer at stage I, how many males were diagnosed at stage II?</p>'),
            array('id' => '3675','question' => '<p>The following pie chart shows the percent distribution of prostate cancer by stage at diagnosis in males in Canada, 2011-2015:</p><p><img alt="" style="height: 277px; width: 260px;" src="https://healthnumeracyproject.com/admin/uploads/1588023729_prostatecancerED2.jpg" /></p><p>True or False: More males were diagnosed with prostate cancer at stage II than at any other stage.</p>'),
            array('id' => '3676','question' => '<p>The following pie charts shows the distribution of psychiatric diagnoses of people who died by suicide among psychiatric inpatients (left) and those in the general population (right):</p><p><img alt="" style="height: 265px; width: 800px;" src="https://healthnumeracyproject.com/admin/uploads/1588096120_suicideED2.jpg" /></p><p>True or False: The proportion of people with schizophrenia who died by suicide was approximately twice as large in the general population than in the population of psychiatric inpatients.</p>'),
            array('id' => '3677','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following pie charts show the main causes of cancer deaths among men and women in OECD (Organisation for Economic Co-operation and Development) countries in 2013:</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height: 222px; width: 460px;" src="https://healthnumeracyproject.com/admin/uploads/1588096270_OCEDED2.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: Colorectal cancer deaths disproportionally affected men and women.</span></span></p>'),
            array('id' => '3678','question' => '<p>The following pie charts show the main causes of avoidable mortality in OECD countries in 2017, by preventable causes of mortality (left) and treatable health causes of mortality (right):</p><p><img alt="" style="height: 307px; width: 600px;" src="https://healthnumeracyproject.com/admin/uploads/1588096403_avoidablemortED2.jpg" /></p><p>Compared to the proportion of cancer cases which were preventable causes of mortality, how many were treatable causes of mortality?</p>'),
            array('id' => '3679','question' => '<p>The following pie charts show the percent distribution of colon and rectum cancer cases by stage at diagnosis in Canada, 2011-2015:</p><p><img alt="" style="height: 229px; width: 460px;" src="https://healthnumeracyproject.com/admin/uploads/1588096614_colonrectumED2.jpg" /></p><p>Fill in the blank: ____ as many rectum cancer cases were diagnosed at an unknown stage compared to colon cancer cases.</p>'),
            array('id' => '3680','question' => '<p>The following pie charts visualize the answers to a survey question &quot;Did you have a flu shot&quot; conducted among people who do not have asthma and who have asthma.</p><p><img alt="" style="height: 171px; width: 420px;" src="https://healthnumeracyproject.com/admin/uploads/1585168217_asthmaflushot.jpg" /></p><p>True or False: Based on this data, the average person in the general population is more likely to get a flu shot than the average person with asthma.</p>'),
            array('id' => '3681','question' => '<p>The following pie chart shows the ages of people with Alzheimer&rsquo;s Dementia in the U.S. in 2018:</p><p><img alt="" style="height: 191px; width: 300px;" src="https://healthnumeracyproject.com/admin/uploads/1588012755_Alzheimers ED2.jpg" /></p><p>True or False: Based on the data, more than half of all individuals with Alzheimer&rsquo;s Dementia are 75 years old or over.</p>'),
            array('id' => '3682','question' => '<p>The following pie chart shows the proportion of dialysis patients in a study who received influenza vaccinations in 2009 and 2010.</p><p><img alt="" style="height: 187px; width: 320px;" src="https://healthnumeracyproject.com/admin/uploads/1588018864_InfluenzavaccED2.jpg" /></p><p>True or False: Patients were more likely to get the influenza vaccination twice than just once.</p>'),
            array('id' => '3683','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">The following pie chart shows the distribution of 10-year tumour-based prevalence for selected cancers in Canada, January 1, 2009:</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height:305px; width:407px" src="https://healthnumeracyproject.com/admin/uploads/1588097373_cancersED3.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or False: Of all cancer types, including those not specified, prostate cancer had the largest 10-year tumour-based prevalence.</span></span></p>'),
            array('id' => '3787','question' => '<p><span style="font-size:14px;">This chart&nbsp;shows COVID-19 death rate by age, as of May 2020. &nbsp;</span></p><p><span style="font-size:14px;"><img alt="" style="height: 349px; width: 440px;" src="https://healthnumeracyproject.com/admin/uploads/1589306470_covidByage.jpg" /></span></p><p><span style="font-size:14px;">True or False: The death rate for people over 80 years old is higher than the death rates of any other age category.</span></p>'),
            array('id' => '3865','question' => '<p>This pie chart displays the nine diseases&nbsp;featured in the 116 original research articles and reviews published in the first five volumes of Geospatial Health.&nbsp; We can see which diseases are the most important by the % of articles dedicated to them.&nbsp; The variable &#39;disease&#39; is what type of variable in this study?</p><p><img alt="" style="height:342px; width:466px" src="https://healthnumeracyproject.com/admin/uploads/1590679045_U2T1L35.jpg" /></p><p>&nbsp;</p>'),
            array('id' => '3882','question' => '<p>This chart displays the number (in millions) and percent (%) of people without health insurance coverage in the United States.</p><p><img alt="" style="width: 560px; height: 504px;" src="https://healthnumeracyproject.com/admin/uploads/1594785120_healthcover.jpg" /></p><p>True or False: With respect to the 2016 baseline for future predictions (blue dashed line), although the number of uninsured people will decrease from 2016 to 2017, the percent of uninsured people will increase from 2016 to 2017.</p>'),
            array('id' => '4078','question' => '<p>This pie chart&nbsp; displays the prevalence of types clinical allergy services provided by clinical immunologists in the United Kingdom.</p><p><img alt="" style="height:354px; width:426px" src="https://healthnumeracyproject.com/admin/uploads/1592672154_catefffgoricalallergy.jpg" /></p><p>Which service accounts for the highest rate of visits?</p>'),
            array('id' => '4202','question' => '<p><span style="font-family:Arial,Helvetica,sans-serif;">Studies investigating the transmission of HIV from improperly discarded needles suggest that such exposure represents a low risk for transmission. This is likely due to the low viability of the virus outside the body. The following pie chart depicts the risk of transmission of HIV per drug injection from a contaminated needle:</span></p><p><span style="font-family:Arial,Helvetica,sans-serif;"><img alt="" style="height:332px; width:294px" src="https://healthnumeracyproject.com/admin/uploads/1593406822_hivnohivhivnohiv.jpg" /></span></p><p><span style="font-family:Arial,Helvetica,sans-serif;">For someone injecting drugs with a needle contaminated with HIV, what is the chance that they will contract HIV?</span></p><p>&nbsp;</p>'),
            array('id' => '4226','question' => '<p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">This bar chart shows smoking prevalence by age in Canada, in 2017.</span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;"><img style="width: 333px; height: 370px;" alt="" src="https://healthnumeracyproject.com/admin/uploads/1597027955_tobaccouseCDN.jpg" /></span></span></p><p><span style="font-size:14px;"><span style="font-family:Arial,Helvetica,sans-serif;">True or false: The rate of current smoking among youth aged 20-24 is about twice the rate for youth aged 15-19.</span></span></p>'),
            array('id' => '4315','question' => '<p>At the start of the day, a HIM professional had 38 inpatient charts to code. By the end of the day, 11 inpatient charts remained not coded.</p><p>Q1. What was the raw decrease of inpatient charts yet to be coded?&nbsp; (Enter the just the value without the unit.)</p><p>Q2. What was the % decrease of inpatient charts. Enter a value without the % sign rounded to 2 decimal places.</p>'),
            array('id' => '4787','question' => '<p>In research scenarios where two variables are involved, the variables can be either categorical (nominal/ordinal) or measurement.&nbsp; This means that there are only 3 options for the pairings of the data</p><p>1. both variables are categorical&nbsp;</p><p>2. both are measurement</p><p>3. one is categorical and the other is measurement</p><p>Given the data analysis output and a statement about the findings decide on which type of pairing the following represent.</p><p>The paneled pie chart below compares the race/ethnicity breakdown of&nbsp;HIV diagnoses among transgender people in the United States&nbsp;between 2009-2014</p><p><img alt="" style="width: 485px; height: 274px;" src="https://healthnumeracyproject.com/admin/uploads/1610731866_2 var lesson 4 transgender-charts-v2a-01-large.png" /></p>'),
            array('id' => '4788','question' => '<p>In research scenarios where two variables are involved, the variables can be either categorical (nominal/ordinal) or measurement.&nbsp; This means that there are only 3 options for the pairings of the data</p><p>1. both variables are categorical&nbsp;</p><p>2. both are measurement</p><p>3. one is categorical and the other is measurement</p><p>Given the data analysis output and a statement about the findings decide on which type of pairing the following represent.</p><p>The paneled pie chart below shows the number of deaths by cause among two cohorts, 25&ndash;34 and 35-44 year old&#39;s, where death by homicide/suicide is 12.3% higher in the&nbsp; 25-34 age cohort.</p><p><img alt="" style="width: 453px; height: 173px;" src="https://healthnumeracyproject.com/admin/uploads/1610732450_2vars lesson 4 num deaths by age.jpg" /></p>')
        );


        foreach ($old_questions as $old_question) {
            $question = \App\Question::where('id', $old_question['id'])->first();
            $question->question = $old_question['question'];
            $question->save();
        }

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
